@local=http://localhost:3001
@localGoogle="http://localhost:3001/api/auth/google"

### CREATE PROFILE

POST  {{local}}/api/profile/Create-profile/
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Mjk4OWViZDgyMGZmZDE4YjEyYTQ4MSIsImVtYWlsIjoiYXJpZWxob2RheWFAZ21haWwuY29tIiwibmFtZSI6IteQ16jXmdeQ15wg15HXnyDXkNeV16giLCJpYXQiOjE3NjQzMzI3Mjd9.KXkFshRyuRet581K3jT8QMOU7hhuKpybrqu2znmfBd8


{
  "fullName": "יצחק בן יצחק",
  "gender": "נקבה",
  "age": 29,
  "height": 173,
  "weight": 80,
  "target": "בריאות כללית",
  "activity": "קל",
  "kosher": true,
  "vegetarian": false,  
  "bodyFat":54,
  "favoFoods": "אוהב עוף על האש, טחינה, אורז מלא וירקות מאודים."
}

### DELETE MANY: 

DELETE  {{local}}/api/profile/Delete-profiles/

### GET ALL PROFILES:

GET  {{localGoogle}}/api/profile/All-profiles/

### SIGN IN

GET  {{local}}/api/users/me

### SIGN IN GOOGLE

GET  {{local}}/


